### route pour enregister un utilisateur
// Demander à l'equipe comment les données du form seront envoyé, form data ou json ? 
POST http://localhost:3000/user
content-type: application/json

{
    "last_name": "33",
    "first_name": "User 01",
    "mail": "frankie@oclock.io",
    "location": " 48.866669, 2.33333",
    "password": "motdepasse tres secret", 
    "profile_picture": "https://fr.web.img6.acsta.net/r_1280_720/newsv7/20/12/07/17/58/1442788.jpg",
    "id": 10


}

### Route pour voir touts les utilisateurs 

GET http://localhost:3000/user


### Route pour voir un utilisateur 

GET http://localhost:3000/user/100


### Route pour supprimer un utilisateur 

DELETE http://localhost:3000/user/9


###############################################

### Route event 

### Route pour créer un event 
POST http://localhost:3000/event
content-type: application/json

{
    "location": "48.856614, 2.3522219",
    "owner_id": 10
}

### Routes pour voir touts les events
GET http://localhost:3000/events

### Route pour voir un evenement 
GET http://localhost:3000/event/4